server:
  port: 8081

spring:
  profiles:
    active: db, core, system
  messages:
    encoding: UTF-8
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: info
#    org.mybatis: debug
    com.hzy.toolman: debug
