toolman:
  uploadPath: D:/Project/Back-End/toolman/uploaded_files/common/
  teach_upload_path: D:/Project/Back-End/toolman/uploaded_files/teach/

spring:
  redis:
    host: 47.98.167.70
    password:
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1